name: CI
on: [push, pull_request, workflow_dispatch]

jobs:
  ubuntu-gcc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run tests
        run: |
          cc nobuild.c -onobuild && ./nobuild
      - name: run examples
        run: |
          ./nobuild examples
        env:
          CC: gcc
          CXX: g++
  ubuntu-clang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run tests
        run: |
          cc nobuild.c -onobuild && ./nobuild
      - name: run examples
        run: |
          ./nobuild examples
        env:
          CC: clang
          CXX: clang
  macos-clang:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: run tests
        run: |
          cc nobuild.c -onobuild && ./nobuild
      - name: run examples
        run: |
          ./nobuild examples
        env:
          CC: clang
          CXX: clang
  windows-msvc:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: seanmiddleditch/gha-setup-vsdevenv@master
      - name: run tests and examples
        shell: cmd
        run: |
          cl nobuild.c && nobuild.exe && nobuild.exe examples
  windows-gcc:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include: [{ msystem: MINGW64, msystem_lower: mingw64, arch: x86_64 }]          
    steps:
      - uses: actions/checkout@v1
        with:
          path: temp
          fetch-depth: 0
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          install: mingw-w64-${{ matrix.arch }}-gcc
          update: true
      - name: update pkgs
        run: |
          msys2 -c 'pacman --noconfirm -Suuy'
          msys2 -c 'pacman --noconfirm -Suu'
      - name: run tests and examples
        run: |
          gcc nobuild.c -onobuild && ./nobuild && ./nobuild examples
        shell: msys2 {0}
        env:
          CC: gcc
          CXX: g++
  windows-clang:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include: [{ msystem: MINGW64, msystem_lower: mingw64, arch: x86_64 }]          
    steps:
      - uses: actions/checkout@v1
        with:
          path: temp
          fetch-depth: 0
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          install: mingw-w64-${{ matrix.arch }}-clang
          update: true
      - name: update pkgs
        run: |
          msys2 -c 'pacman --noconfirm -Suuy'
          msys2 -c 'pacman --noconfirm -Suu'
      - name: run tests and examples
        run: |
          clang nobuild.c -onobuild && ./nobuild && ./nobuild examples
        shell: msys2 {0}
        env:
          CC: clang
          CXX: clang
